"""fbl_auth — Stage 9: MCP accounts, tokens, rate limiting, usage metering (00_accounts)."""

from __future__ import annotations

from .accounts import (
    ACCOUNTS_CONTAINER,
    Account,
    RateDecision,
    TokenRecord,
    Usage,
    check_rate_limit,
    hash_token,
    issue_token,
    quota_for,
    record_usage,
    signup,
    validate,
)
from .api_handlers import (
    regenerate_request,
    signup_request,
    unsubscribe_request,
    verify_request,
)
from .email import AcsEmailSender, EmailSender, NullEmailSender, email_sender_from_settings
from .metrics import bump_metric, read_metric
from .oauth import (
    ACCESS_TTL_SEC,
    CODE_TTL_SEC,
    OAUTH_CLIENTS,
    OAUTH_CODES,
    OAUTH_PENDING,
    OAUTH_TOKENS,
    REFRESH_TTL_SEC,
    AuthorizationCode,
    BearerToken,
    OAuthClient,
    PendingAuth,
    consume_code,
    consume_pending_auth,
    consume_refresh,
    create_pending_auth,
    get_client,
    get_or_create_account_by_email,
    issue_code,
    issue_token_pair,
    register_client,
    revoke,
    validate_bearer,
    verify_pkce,
)
from .signup_flow import (
    DISPOSABLE_DOMAINS,
    PendingSignup,
    check_ip_throttle,
    find_accounts_by_email,
    is_plausible_email,
    regenerate,
    request_verification,
    unsubscribe,
    verify,
)

__all__ = [
    "ACCESS_TTL_SEC",
    "ACCOUNTS_CONTAINER",
    "CODE_TTL_SEC",
    "DISPOSABLE_DOMAINS",
    "OAUTH_CLIENTS",
    "OAUTH_CODES",
    "OAUTH_PENDING",
    "OAUTH_TOKENS",
    "REFRESH_TTL_SEC",
    "Account",
    "AcsEmailSender",
    "AuthorizationCode",
    "BearerToken",
    "EmailSender",
    "NullEmailSender",
    "OAuthClient",
    "PendingAuth",
    "PendingSignup",
    "RateDecision",
    "TokenRecord",
    "Usage",
    "bump_metric",
    "check_ip_throttle",
    "check_rate_limit",
    "consume_code",
    "consume_pending_auth",
    "consume_refresh",
    "create_pending_auth",
    "email_sender_from_settings",
    "find_accounts_by_email",
    "get_client",
    "get_or_create_account_by_email",
    "hash_token",
    "is_plausible_email",
    "issue_code",
    "issue_token",
    "issue_token_pair",
    "quota_for",
    "read_metric",
    "record_usage",
    "regenerate",
    "regenerate_request",
    "register_client",
    "request_verification",
    "revoke",
    "signup",
    "signup_request",
    "unsubscribe",
    "unsubscribe_request",
    "validate",
    "validate_bearer",
    "verify",
    "verify_pkce",
    "verify_request",
]
